;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        dabbrev-expand
        delete-horizontal-space
        delete-indentation
        down-list
        forward-sexp
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        sp-backward-delete-char
        sp-delete-char
        sp-kill-hybrid-sexp
        sp-kill-region
        sp-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        hydra-all/body
        hydra-all/hydra-multiple-cursors/body-and-exit
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/insert-letters-and-exit
        hydra-multiple-cursors/mc/mark-all-dwim-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-next-lines
        hydra-multiple-cursors/mc/mark-next-lines-and-exit
        hydra-multiple-cursors/mc/mark-previous-like-this
        major-mode-hydra
        mc/mark-next-lines
        org-cycle
        phi-search-backward
        toggle-input-method
        ))
