;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        sp-backward-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        mc/mark-next-lines
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-all-dwim-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/mark-next-lines-and-exit
        ))
